# Generated by Django 3.0.2 on 2021-06-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('createdDate', models.DateField()),
                ('eventTime', models.DateField()),
                ('about', models.TextField()),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
