# Generated by Django 3.0.2 on 2021-08-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.TextField()),
                ('eventDate', models.DateField()),
                ('eventDiscription', models.CharField(max_length=250)),
            ],
        ),
    ]
